-   id: pylint-py3k
    name: Python 3 porting mode check
    description: This hook use pylint --py3k option to check Python 3 porting.
    entry: ./py3k.py
    language: script
    files: \.py$
-   id: pylint-score-limit
    name: Pylint Score Limit
    description: This hook runs pylint and checks it's score
    entry: ./score_limit.py
    language: script
    files: \.py$
-   id: pylint-pass-with-displayed-warnings
    name: Pylint Pass With Displayed Warnings
    description: This hook runs pylint and still allows it to pass if certain warning codes are displayed
    entry: ./score_limit.py
    language: script
    files: \.py$
-   id: python-check-no-print-statments
    name: Check no Python print statements
    description: 'Enforce that print statements are not committed. If intentional, print statements can be allowed by: # allow-print '
    entry: '^\s*(?# allow spaces in front of print, but exclude anything that is text so that a function could end in print )print\s*(?# allow spaces in between the end of print and the open parentheses )\((?!.* \# allow-print.*)'
    language: pygrep
    types: [python]
-   id: vuejs-check-no-console-log-statments
    name: Check no console log statements
    description: 'Enforce that console.log statements are not committed. If intentional, statements can be allowed by: // allow-log '
    entry: '^\s*(?# allow spaces in front of console, but exclude anything that is text so that a function could end in console )console\.log\((?!.* \/\/.* allow-log.*)'
    language: pygrep
    types: [file]
    files: \.(js|vue)$    
    